#! /bin/sh

### BEGIN INIT INFO
# Provides:          Temperature reading
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Temperature reading service
# Description: Temperature reading service
### END INIT INFO

# Carry out specific functions when asked to by the system
case "$1" in
    start)
       echo "Starting info service"
       # run application you want to start
      /home/debian/bb-temp/bin/program.o & serverpsid=$!
       ;;
    stop)
      echo "Stopping info service"
      # kill application you want to stop
      kill $serverpsid
      ;;
    *)
      echo "Usage: /etc/init.d/tempservice{start|stop}"
      exit 1
      ;;
esac

exit 0
